# Generated by Django 5.2.1 on 2025-06-20 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='姓氏')),
                ('first_name', models.CharField(max_length=100, verbose_name='名字')),
                ('email', models.EmailField(max_length=254, verbose_name='電郵')),
                ('message', models.TextField(verbose_name='查詢內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交時間')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='聯絡電話')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
        ),
    ]
