# Generated by Django 5.2.1 on 2025-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('photo_small', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_large', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('introduction', models.TextField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('is_hots', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
            ],
        ),
    ]
