# Generated by Django 5.2.1 on 2025-06-17 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.CharField(max_length=100)),
                ('shopCartId', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField()),
                ('sub_total', models.DecimalField(decimal_places=1, max_digits=2)),
                ('unit_price', models.DecimalField(decimal_places=1, max_digits=2)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
