# Generated by Django 5.2.1 on 2025-06-20 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('carts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='user_id',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='userId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='bookId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.book'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='shopCartId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carts.shopcart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
