# Generated by Django 5.2.1 on 2025-06-21 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('carts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('receipient', models.CharField(max_length=50)),
                ('receipient_phone', models.CharField(max_length=20)),
                ('shipping_address', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=5)),
                ('shipping_status', models.CharField(max_length=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shopCartId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carts.shopcart')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CartID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carts.cartitem')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.book')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
